-- Optimized Neo-tree configuration for performance and responsiveness
-- Focus: Lazy loading, smart filtering, and caching

return {
  'nvim-neo-tree/neo-tree.nvim',
  version = '*',
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-tree/nvim-web-devicons',
    'MunifTanjim/nui.nvim',
    'antosha417/nvim-lsp-file-operations',
  },
  cmd = 'Neotree',
  keys = {
    { '\\', ':Neotree reveal left<CR>', desc = 'NeoTree reveal', silent = true },
  },
  opts = {
    close_if_last_window = false,
    popup_border_style = 'rounded',
    enable_git_status = true,
    enable_diagnostics = false,
    sort_case_insensitive = true,
    sources = { 'filesystem', 'buffers', 'git_status' },
    source_selector = {
      winbar = true,
      content_layout = 'center',
      sources = {
        { source = 'filesystem', display_name = ' 󰉓 Files ' },
        { source = 'buffers', display_name = ' 󰈙 Buffers ' },
        { source = 'git_status', display_name = ' 󰊢 Git ' },
      },
    },
    default_source = 'filesystem',
    filesystem = {
      bind_to_cwd = false,
      cwd_target = 'tab',
      follow_current_file = { enabled = false },
      use_libuv_file_watcher = true,
      group_empty_dirs = true,
      scan_mode = 'shallow', -- Performance: use shallow scan for large directories
      window = {
        mappings = {
          ['\\'] = 'close_window',
          ['o'] = 'open',
          ['<CR>'] = 'open',
          ['<2-LeftMouse>'] = 'open',
          ['e'] = 'open',
          ['s'] = 'open_split',
          ['v'] = 'open_vsplit',
          ['t'] = 'open_tabnew',
          ['a'] = 'add',
          ['d'] = 'delete',
          ['r'] = 'rename',
          ['c'] = 'copy_to_clipboard',
          ['x'] = 'cut_to_clipboard',
          ['p'] = 'paste_from_clipboard',
          ['m'] = 'move',
          ['q'] = 'close_window',
          ['R'] = 'refresh',
          ['?'] = 'show_help',
          ['<'] = 'prev_source',
          ['>'] = 'next_source',
          ['i'] = 'show_file_details',
        },
      },
      filtered_items = {
        visible = false,
        hide_dotfiles = false,
        hide_gitignored = true,
        hide_hidden = true,
        never_show = {
          '.git',
          '.DS_Store',
          'thumbs.db',
          '__pycache__',
          '.pytest_cache',
          '.venv',
          'node_modules',
          '.next',
          '.nuxt',
          'dist',
          'build',
        },
        always_show = { '.gitignored' },
      },
    },
    buffers = {
      follow_current_file = { enabled = false },
      group_empty_dirs = true,
    },
    git_status = {
      window = {
        position = 'float',
      },
    },
    window = {
      width = 30,
      mapping_options = {
        noremap = true,
        nowait = true,
      },
      mappings = {
        ['<space>'] = {
          'toggle_node',
          nowait = true,
        },
        ['<2-LeftMouse>'] = 'open',
        ['<cr>'] = 'open',
        ['S'] = 'open_split',
        ['s'] = 'open_vsplit',
        ['C'] = 'close_node',
        ['z'] = 'close_all_nodes',
        ['a'] = {
          'add',
          config = {
            show_path = 'relative',
          },
        },
        ['A'] = 'add_directory',
        ['d'] = 'delete',
        ['r'] = 'rename',
        ['y'] = 'copy_to_clipboard',
        ['x'] = 'cut_to_clipboard',
        ['p'] = 'paste_from_clipboard',
        ['c'] = 'copy',
        ['m'] = 'move',
        ['q'] = 'close_window',
        ['R'] = 'refresh',
        ['?'] = 'show_help',
        ['<'] = 'prev_source',
        ['>'] = 'next_source',
      },
    },
  },
}
